<template>
  <v-app>
    <v-content app>
      <nuxt />
    </v-content>
  </v-app>
</template>

<script>
export default {
  data() {
    return {}
  }
}
</script>

<style lang="scss">
@import url('https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700&display=swap');

html,
body {
  height: 100%;
  width: 100%;
}

.application {
  font-family: 'Montserrat', sans-serif;
}

.v-parallax__content {
  padding: 0 !important;
}

.v-parallax__image {
  // margin-bottom: -300px;
}

@keyframes startUpName {
  0% {
    height: 0px;
  }
  100% {
    height: 40px;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2019-5-22 20:50:3
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-pop-up-top
 * ----------------------------------------
 */

@keyframes text-pop-up-top {
  0% {
    -webkit-transform: translateY(0);
    transform: translateY(0);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    text-shadow: none;
    opacity: 0;
  }
  100% {
    -webkit-transform: translateY(-20px);
    transform: translateY(-20px);
    -webkit-transform-origin: 50% 50%;
    transform-origin: 50% 50%;
    opacity: 1;
    text-shadow: 0 1px 0 #cccccc, 0 2px 0 #cccccc, 0 3px 0 #cccccc,
      0 4px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.3);
  }
}

@keyframes tracking-in-expand {
  0% {
    letter-spacing: -0.5em;
    opacity: 0;
  }
  40% {
    opacity: 0.6;
  }
  100% {
    opacity: 1;
  }
}
</style>
